### ISSUE TITLE
Suggestion: How about using KV with Fresh Project Manager

### ISSUE THREAD

**Issue by hashrock** [xyntechx/NexLiber-Projects#10]
Deno Deploy recently implemented a [KV store](https://deno.com/kv). You can easily save JSON to the server. Fresh Project Manager stores state in local storage, but using KV instead would make it a more practical application.

**Comment by xyntechx** [comment]
Hi @hashrock! Thanks for the feedback! While I won't update the project hence Workbook since it has already been published on https://nexliber.com, I will keep that in mind for future projects. Tysm!
